FROM nginx:latest
LABEL MAINTAINER="sj0225@icloud.com"

COPY default.conf /etc/nginx/conf.d/


# 安装nginx的配置文件，支持https和部分站点重定向
#COPY nginx/ssl/caogo.cn.crt /etc/nginx/ssl/caogo.cn.crt
#COPY nginx/ssl/caogo.cn.key /etc/nginx/ssl/caogo.cn.key
#
#COPY nginx/scrapyd_proxy.conf /etc/nginx/conf.d/
#COPY nginx/ssl.conf /etc/nginx/conf.d/